

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu_mag?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    cn.ingahi: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


