

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu_mag
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    cn.ingahi: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


